class Translation(object):

    HELP_TEXT = """<b><u>BASIC COMMANDS</u></b>\n\n • /start :- Check Iam Alive\n • /help :- More Details\n • /about :- About Me\n • /sub :- Support \n • /stats :- User Count""" 
    START_TEXT = """👋Hey {}\n\n Click On The /Subscribe command\nSubscribe to the update channel to learn about my updates and activity...\n\n🕵‍♂ Developer : <a href="https://t.me/{}">★  ɱɧɖ ɬɧąŋʑɛɛཞ ★</a>"""       
    ABOUT_TEXT = """<b>🥱 My Name : MHD CREATION🕵‍♂ Developer : <a href='https://t.me/mhd_thanzeer'>★ ɱɧɖ ɬɧąŋʑɛɛཞ ★</a>📚 Library : 𝙿𝚈𝚁𝙾𝙶𝚁𝙰𝙼🖥 Language : 𝙿𝚈𝚃𝙷𝙾𝙽 𝟹🎪 Data Base : 𝙼𝙾𝙽𝙶𝙾 𝙳𝙱🔋 Bot Group : @wolfpackmedia </b>"""
    FSUB_TEXT = """ഹേയ് {} തായേ കാണുന്ന ചാനലിൽ നിങ്ങൾ ഇല്ല അത് കൊണ്ട് നിങ്ങൾക് സിനിമ കിട്ടില്ല...\nസിനിമ കിട്ടാനായി താഴെ കാണുന്ന 🔔 Join എന്ന ബട്ടനിൽ ക്ലിക്ക് ചെയ്തു ഞങ്ങളുടെ മെയിൻ ചാനലിൽ ജോയിൻ ചെയ്യുക എങ്കിൽ മാത്രമേ നിങ്ങൾക്ക് മൂവി ഈ ബോട്ട് വഴി ലഭിക്കുകയുള്ളു. അതു കഴ്ഞ്ഞു തായേ കാണുന്ന 👉"Try again"👈 എന്നുള്ളതിൽ ക്ലിക്ക് ചെയ്തു Start കൊടുത്താൽ നിങ്ങൾക്ക് മൂവി കിട്ടുന്നതാണ്...😁😁"""
    FILTER_TEXT = """<b><u>Manual Filter</u></b>\n\n• Add me as admin in your group and start filtering:\n\n<b><u>NOTE:</u></b>\n\n1. Me should have admin privillage.\n2. only admins can add filters in a chat.\n3. alert buttons have a limit of 64 characters.\n\n<b><u>Commands and Usage:</u></b>\n• /addfilter - Add filter for name\n• /filters - List all filters in chat\n• /delfilters - Delete filter\n• /delallfilters - Delete entire filters (Group Owner Only!)"""
    AUTOFILTER_TEXT = """<b><u>Auto Filter</u></b>\n\n<b><u>🤖 Bot Commands 🤖</u></b>\n  <code>(Works Only In Groups):</code>\n\n<b><u>Add CMD</u></b>\n  ☞ <code>/addchannel</code> <b>chat_id</b>\n  ☞ <code>/addchannel</code>\n<b><u>Deleted CMD</u></b>\n  ☞ <code>/delchannel</code> <b>chat_id</b>\n  ☞ <code>/delchannel</code> <b>@Mo_Tech_YT</b>\n<b>- To disconnect A Group With A Channel</i></b>"""
    AUTOFILTER_TEXT2 = """<b><u>📃 MAIN INFORMATION 📃</u></b>\n\n  ☞ <b>/settings</b> -  <b>This Command Will Display You A Settings Pannel Instance Which Can Be Used To Tweek Bot's Settings Accordingly</b>\n\n  ☞ <b>Channel</b> - <b>Button Will Show You All The Connected Chats With The Group And Will Show Buttons Correspnding To There Order For Furthur Controls</b>\n\n  ☞ <b>Filter Types</b> - <b>Button Will Show You The 3 Filter Option Available In Bot... Pressing Each Buttons Will Either Enable or Disable Them And This Will Take Into Action As Soon As You Use Them Without The Need Of A Restart</b>      \n\n  ☞ <b>Configure</b> - <b>Button Will Helps You To Change No. of Pages/ Buttons Per Page/ Total Result Without Acutally Editing The Repo... Also It Provide Option To Enable/Disable For Showing Invite Link In Each Results</b>"""
    DYNO_TEXT = """😍 Total Users {}\n😁 Total Chats {}\n👏 Total Manul Filters {}\n⏳ Bot Update Time {}"""
    INFORMATION_TEXT = """<b><u>Extra Modes</u></b>\n\n<b>NOTE:</b>\nthese are the extra features of Donlee Robot v2\n\n<b><u>Work Only Group:</u></b>:\n\n• No inline Message\n• No Forword Message\n\n<b><u>CMD Work Only Group:</u></b>\n• /report - report To admin\n\n<b><u>Commands and Usage:</u></b>\n• /id - get id about a user and group.\n• /info  - get information about a user and Group.\n• /status - Get Bot Status"""
    CREDITS_TEXT = """🕵‍♂ Developer : <a href='https://t.me/mhd_thanzeer'>★  ɱɧɖ ɬɧąŋʑɛɛཞ ★</a>"""
    CONNECTION_TEXT = """<b><u>Connection</u></b>\n\n- Used to connect bot to PM for managing filters \n- it helps to avoid spamming in groups.\n\nNOTE:\n1. Only admins can add a connection.\n2. Send /connect for connecting me to ur PM\n\nCommands and Usage:\n• /connect  - connect a particular chat to your PM\n• /disconnect  - disconnect from a chat\n• /connections - list all your connections"""
    DEV_TEXT = """<b>🕵‍♂ Developer : <a href='https://t.me/mhd_thanzeer'>★  ɱɧɖ ɬɧąŋʑɛɛཞ ★</a></b>"""
    GROUP_ADMIN_TEXT = """<b><u>Group Commands</u></b>\n\n<b><u>Bot Master</u></b>\n• /broadcast - Replay Any Message\n\n<b><u>Group Admin Only</u></b>\n• /ban - Reply Any User Text\n• /unban - Reply Banned User Text"""
    SUB_TEXT = """Join Share Maximum Support"""
    SPELLING_TEXT = """Hey {} Check Your Spelling"""
    STATUS_TEXT = """<b><u>Bot Status</u></b>\nTotal Users <b>{}</b>"""
    SOURCE_TEXT = """😐"""
